### ISSUE TITLE
请问能提供psenet在ic17上pretrain的log吗？

### ISSUE THREAD

**Issue by xmy0916** [open-mmlab/mmocr#102]
请问能提供psenet在ic17上pretrain的log吗？感谢！或者能告知一下训练的细节吗

**Comment by innerlee** [comment]
Sure, we will add more models to modelzoo. You can modify configs and try it yourself since there are ic17 configs https://mmocr.readthedocs.io/en/latest/textdet_models.html#icdar2017

**Comment by xmy0916** [comment]
@innerlee 您好，链接只有ic15上的log，我想看看pretrain model在ic17上训练的log，请问有吗？

**Comment by cuhk-hbsun** [comment]
@xmy0916 The training log and config are attached. Since it is old, we are re-training on IC17 and will release the latest log file soon.

To generate `instances_training.txt` from `instances_training.json`, use cmd `python tools/data/textdet/coco_to_line_dict.py --in-path instances_training.json --out-path instances_training.txt`

[psenet_ic17_log.zip](https://github.com/open-mmlab/mmocr/files/6471657/psenet_ic17_log.zip)

**Comment by cuhk-hbsun** [comment]
@xmy0916 Btw, we use 2 GeForce GTX 1080Ti GPUs.

**Comment by xmy0916** [comment]
谢谢



---原始邮件---
发件人: "Hongbin ***@***.***&gt;
发送时间: 2021年5月13日(周四) 下午5:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-mmlab/mmocr] 请问能提供psenet在ic17上pretrain的log吗？ (#102)




 
@xmy0916 The training log and config are attached. Since it is old, we are re-training on IC17 and will release the latest log file soon.
 
To generate instances_training.txt from instances_training.json, use cmd python tools/data/textdet/coco_to_line_dict.py --in-path instances_training.json --out-path instances_training.txt
 
psenet_ic17_log.zip

**Comment by cuhk-hbsun** [comment]
fix
