### ISSUE TITLE
TorchServe dockerfile does not exist

### ISSUE THREAD

**Issue by Hegelim** [open-mmlab/mmocr#1067]
I am following the instructions here:
https://mmocr.readthedocs.io/en/latest/model_serving.html

I am trying to build the docker image from mmocr-serve:
```
docker build -t mmocr-serve:latest docker/serve/
```

However, there is no such directory docker/serve/
Is this a bug?

**Comment by gaotongxiao** [comment]
Yes, thanks for catching it. We'll add it back soon, but it may take some time. If you need it urgently, you may try downloading the `docker/serve` directory from mmdet (https://github.com/open-mmlab/mmdetection/blob/master/docker/serve/) and add `RUN pip install mmocr` to https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/docker/serve/Dockerfile#L31, then everything should work fine. Since this solution has not been thoroughly tested, we would appreciate any feedback as you adopt it.

**Comment by gaotongxiao** [comment]
Thanks for sharing the details! Would you like to raise a PR to supplement these missing files back?

**Comment by Hegelim** [comment]
Happy to contribute. Just created a PR here: https://github.com/open-mmlab/mmocr/pull/1073
Did I miss anything?
