### ISSUE TITLE
How to select `dict_type`

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1113]
`MMOCR` bundled with helper to convert between text, index and tensor for text recognize pipeline. Currently there are four `dict_type` inclusive  `DICT36`, `DICT37`, `DICT90` and `DICT91`

```
 dicts = dict(
        DICT36=tuple('0123456789abcdefghijklmnopqrstuvwxyz'),
        DICT90=tuple('0123456789abcdefghijklmnopqrstuvwxyz'
                     'ABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()'
                     '*+,-./:;<=>?@[\\]_`~'),
        # With space character
        DICT37=tuple('0123456789abcdefghijklmnopqrstuvwxyz '),
        DICT91=tuple('0123456789abcdefghijklmnopqrstuvwxyz'
                     'ABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()'
                     '*+,-./:;<=>?@[\\]_`~ '))
```

However, what is the selection criteria for each of this `dict_type`?

Say for example, I am interested to recognize characters from `0~9` , `A~Z` and `a-z` only and no space, 

1. should I select `DICT90`, or 
2. Hard [modify any of the dict](https://github.com/open-mmlab/mmocr/issues/858#issuecomment-1074305772), or
3. is it advisable to create new `dict_type` 

`DICT62=tuple('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ') # 62 characters?`

Assuming, we go for the third approach `DICT62`. The next question is how to assign newly defined `dict_type` in the `label_converter`?. Take for example the `crnn` base `cfg`

https://github.com/open-mmlab/mmocr/blob/72a79f9350277566caae2fdf3ab9cd614f313d28/configs/textrecog/crnn/crnn_toy_dataset.py#L8-L9

From this line

https://github.com/open-mmlab/mmocr/blob/72a79f9350277566caae2fdf3ab9cd614f313d28/mmocr/models/textrecog/convertors/base.py#L33

I got the impression the `label_convertor` can be modified as
```
label_convertor = dict(
    type='CTCConvertor', dict_type=None,dict_list=DICT62, with_unknown=False, lower=True) # Note> I am not sure what with_unknown, lower, mean
```

**Comment by Mountchicken** [comment]
Hi @balandongiv 
Adding a DICT62 is the right way to go.

Here is the meaning of `with_unknown` and `lower`
- `with_unknown`:  There may be some characters in the dataset that do not belong to DICT90, such as Chinese characters or some special characters like `¥`, then this situation requires the use of `with_unknown=True`. Those unknown characters are all represented as `<UNK>` category. For example, let's say `hello` is converted to indexes of `1 2 3 4 5`, then `he￥你lo` will be converted to indexes of `1 92 92 4 5`, where 92 represents the index of `<UNK>`. `with_unknown` is always recommended to be set to True, because it is difficult to know if a DICT covers all character classes in the dataset.
- `lower`: lower stands for converting all uppercase letters in the dataset to lowercase. For example, when using `DICT36`, lower can be set to True.

**Comment by balandongiv** [comment]
Thanks for the lengthy and detail explanation @Mountchicken .

Assume the requirement above, whereby to recognize characters from `0~9` , `A~Z` and `a-z` only and no space, the `label_convertor ` can be assigned as follow

label_convertor = dict(
    type='CTCConvertor', dict_type=None,dict_list=DICT62, with_unknown=True, lower=False)

Note that `lower` is equal to `False`  assume the application is `case` sensitive (`A~Z`).
