### ISSUE TITLE
Usage on MacOS

### ISSUE THREAD

**Issue by hlib-koshurnykov-deepsee** [open-mmlab/mmocr#119]
Is there any chance to use this on MacOS?

**Comment by hlib-koshurnykov-deepsee** [comment]
Or maybe some way to use only CPU instead of GPU

**Comment by innerlee** [comment]
I don't have a mac, but if you can install mmcv on mac, then you can install mmocr.

Some model needs gpu, some does not. You may try different combinations using the demo code https://github.com/open-mmlab/mmocr/blob/main/demo/ocr_image_demo.py

**Comment by FraPochetti** [comment]
I have the same question as @hlib-koshurnykov-deepsee.
@innerlee the issue is that on Mac we cannot install the cudatoolkit.
E.g. I am installing `mmcv` using `pip install mmcv-full=="1.3.1" -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.8.1/index.html`.
Then I install `mmdet` and `mmocr` as explained [here](https://github.com/open-mmlab/mmocr/blob/main/docs/install.md).

When everything is done, to check if things work, I run `python demo/ocr_image_demo.py demo/demo_text_det.jpg demo/output.jpg`, which throws `AssertionError: Torch not compiled with CUDA enabled`.

**Comment by innerlee** [comment]
Ahh I see, the reason is that some mac does not have nvidia gpu, right?

**Comment by FraPochetti** [comment]
Exactly

**Comment by FraPochetti** [comment]
@innerlee we have tried installing on Colab without a GPU and we get the same error.
I am confused, is CUDA a prerequisite for MMOCR?
eg even not on Macos, the library won't work on CPU only systems?

**Comment by innerlee** [comment]
DBNet needs `ModulatedDeformConv`, which is not implemented on cpu yet. So some models will not run on cpu-only systems. We will give a list for cpu/gpu compatibility of models, and will try to make partial support for cpu-only environments.

**Comment by FraPochetti** [comment]
Thanks a lot

**Comment by cuhk-hbsun** [comment]
fix

**Comment by FraPochetti** [comment]
> fix

@cuhk-hbsun does this mean CUDA is not a hard req anymore?
