### ISSUE TITLE
Punctuation in English Datasets

### ISSUE THREAD

**Issue by bely66** [open-mmlab/mmocr#1269]
I'm trying different recognition models with English on MJSynth Dataset.
What I noticed is there's no punctuation present in the dataset.
is there any available datasets which have punctuation present?

**Comment by xinke-wang** [comment]
Hi, MJSynth is a synthetic dataset, it is possible to generate texts with punctuation if you want. You may check their code [here](https://github.com/ankush-me/SynthText). Otherwise, if you would like to use some off-the-shelf datasets including punctuations, you may check [textocr](https://mmocr.readthedocs.io/en/latest/datasets/recog.html#textocr),
