### ISSUE TITLE
Does abinet support vertical text recognition?

### ISSUE THREAD

**Issue by ahsdx** [open-mmlab/mmocr#1270]
Does abinet method (or any other method) support vertical text recognition? What should I do if I want to recognize vertical text? Looking forward to your reply! Thank you!

**Comment by Mountchicken** [comment]
Hi @ahsdx 
Currently, all recognition algorithms are unable to recognize vertical text due to two drawbacks:
- `Dataset problem`: The two commonly used training sets `MJ` and `ST` lack vertical text samples.
- `Pipeline problem`: For the text recognition task, to have a unified image shape for batch training, we will resize the height of the text image to a fixed size, such as 32 or 48, and then scale the width equally with padding. This will squeeze the vertical text and make it unrecognizable.

To recognize verticle text, we need to solve the above problems, and here are some suggestions.
- Prepare enough verticle text samples.
- Design a new pipeline, that when the image is detected as vertical text, for example, if the height of the image is twice the width, then the image is automatically rotated by 90 degrees

**Comment by ahsdx** [comment]
> Hi @ahsdx Currently, all recognition algorithms are unable to recognize vertical text due to two drawbacks:
> 
> * `Dataset problem`: The two commonly used training sets `MJ` and `ST` lack vertical text samples.
> * `Pipeline problem`: For the text recognition task, to have a unified image shape for batch training, we will resize the height of the text image to a fixed size, such as 32 or 48, and then scale the width equally with padding. This will squeeze the vertical text and make it unrecognizable.
> 
> To recognize verticle text, we need to solve the above problems, and here are some suggestions.
> 
> * Prepare enough verticle text samples.
> * Design a new pipeline, that when the image is detected as a vertical text, for example, if the height of the image is twice the width, then the image will automatically be rotated by 90 degrees

Thank you very much for your reply. I'll think about it carefully.
