### ISSUE TITLE
Hello, I would like to ask you about the following error when training the dbnet model on the ICDAR2017 dataset。

### ISSUE THREAD

**Issue by ViviKing414** [open-mmlab/mmocr#1388]
raise TopologicalError(
shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7f63038f4520>

**Comment by xinke-wang** [comment]
Hi, this error may caused due to [invalid polygonal bounding boxes](https://stackoverflow.com/questions/20833344/fix-invalid-polygon-in-shapely) with self-intersection included in the annotation of the dataset.

If you are using [MMOCR 1.x version](https://github.com/open-mmlab/mmocr/tree/dev-1.x), you can directly add our `FixInvalidPolygon` transform to the training/testing pipeline, which will automatically fixes the invalid shapes.

https://github.com/open-mmlab/mmocr/blob/87f15b3135104db5cd104001a129ca2afe185094/mmocr/datasets/transforms/textdet_transforms.py#L119

If you are using the MMOCR 0.x version, we recommend you to write a script to filter out the invalid samples or fix them, take the following codes as an example.

```python
# if you want to filter out the invalid polygons, simply replace them with [x, y, x+w, y, x+w, y+h, x, y+h]
box = [0, 0, 3, 3]
polygon = Polygon([(0,0), (0,3), (3,3), (3,0), (2,0), (2,2), (1,2), (1,1), (2,1), (2,0), (0,0)])
if not polygon.is_valid:
    x, y, w, h = box
    polygon = [x, y, x+w, y, x+w, y+h, x, y+h]

# or you can mark this sample as ignored
if not polygon.is_valid:
    ignored = 1
```

**Comment by ViviKing414** [comment]
Thank you very much for your answer. I'll try it out right away

**Comment by ViviKing414** [comment]
> Hi, this error may caused due to [invalid polygonal bounding boxes](https://stackoverflow.com/questions/20833344/fix-invalid-polygon-in-shapely) with self-intersection included in the annotation of the dataset.
> 
> If you are using [MMOCR 1.x version](https://github.com/open-mmlab/mmocr/tree/dev-1.x), you can directly add our `FixInvalidPolygon` transform to the training/testing pipeline, which will automatically fixes the invalid shapes.
> 
> https://github.com/open-mmlab/mmocr/blob/87f15b3135104db5cd104001a129ca2afe185094/mmocr/datasets/transforms/textdet_transforms.py#L119
> 
> If you are using the MMOCR 0.x version, we recommend you to write a script to filter out the invalid samples or fix them, take the following codes as an example.
> 
> ```python
> # if you want to filter out the invalid polygons, simply replace them with [x, y, x+w, y, x+w, y+h, x, y+h]
> box = [0, 0, 3, 3]
> polygon = Polygon([(0,0), (0,3), (3,3), (3,0), (2,0), (2,2), (1,2), (1,1), (2,1), (2,0), (0,0)])
> if not polygon.is_valid:
>     x, y, w, h = box
>     polygon = [x, y, x+w, y, x+w, y+h, x, y+h]
> 
> # or you can mark this sample as ignored
> if not polygon.is_valid:
>     ignored = 1
> ```

As for the MMOCR version, I noticed that the latest official version is 0.6.1, 1. X. What does it mean?

**Comment by ViviKing414** [comment]
> Hi, this error may caused due to [invalid polygonal bounding boxes](https://stackoverflow.com/questions/20833344/fix-invalid-polygon-in-shapely) with self-intersection included in the annotation of the dataset.
> 
> If you are using [MMOCR 1.x version](https://github.com/open-mmlab/mmocr/tree/dev-1.x), you can directly add our `FixInvalidPolygon` transform to the training/testing pipeline, which will automatically fixes the invalid shapes.
> 
> https://github.com/open-mmlab/mmocr/blob/87f15b3135104db5cd104001a129ca2afe185094/mmocr/datasets/transforms/textdet_transforms.py#L119
> 
> If you are using the MMOCR 0.x version, we recommend you to write a script to filter out the invalid samples or fix them, take the following codes as an example.
> 
> ```python
> # if you want to filter out the invalid polygons, simply replace them with [x, y, x+w, y, x+w, y+h, x, y+h]
> box = [0, 0, 3, 3]
> polygon = Polygon([(0,0), (0,3), (3,3), (3,0), (2,0), (2,2), (1,2), (1,1), (2,1), (2,0), (0,0)])
> if not polygon.is_valid:
>     x, y, w, h = box
>     polygon = [x, y, x+w, y, x+w, y+h, x, y+h]
> 
> # or you can mark this sample as ignored
> if not polygon.is_valid:
>     ignored = 1
> ```

Regarding the MMOCR version, is there any difference between the 1. X version and the mmocr default version?

**Comment by ViviKing414** [comment]
Excuse me again, when training in version 1.x, ImportError: cannot import name 'register_all_modules' from 'mmocr.utils' 。

**Comment by xinke-wang** [comment]
Hi, 

1.x is the latest major update that MMOCR has released, which introduces many new features (check our latest document for more details [English Doc](https://mmocr.readthedocs.io/en/dev-1.x/get_started/overview.html)/[Chinese Doc](https://mmocr.readthedocs.io/zh_CN/dev-1.x/get_started/overview.html)). The 0.x version will be deprecated at the end of this year, hence we recommend users transfer to the 1.x version.

Since the 1.x version relies on the new [MMEngine](https://github.com/open-mmlab/mmengine), it does not share the same running env with the 0.x version. You have to install it following our [installation guide](https://github.com/open-mmlab/mmocr/tree/dev-1.x#installation).
