### ISSUE TITLE
batch prediction for bbox images recognition

### ISSUE THREAD

**Issue by mrtunguyen** [open-mmlab/mmocr#157]
I think we can improve the inference time by doing the batch prediction instead of the current one when running bbox images recognition.
https://github.com/open-mmlab/mmocr/blob/5054a3f78de669daa34dac952395e96ca7f983a7/demo/ocr_image_demo.py#L20

**Comment by cuhk-hbsun** [comment]
Thanks for your sugguestion. Since `augmentation_test` (some methods use, like `configs/textrecog/sar/sar_r31_parallel_decoder_academic.py` in line57) not support batch_mode currently, it cannot do batch prediction to support all recognize frameworks.
It will be better if you want to be a contributor to improve it.

**Comment by sbugallo** [comment]
Hi @mrtunguyen, I opened a PR (#86) a few days ago with this feature. Can you try it and give some feedback?

**Comment by cuhk-hbsun** [comment]
@mrtunguyen hi, I have updated the demo script `ocr_image_demo.py`, please pull the latest code and have a try.
