### ISSUE TITLE
文本识别模型测试时，标注里有空格（图片名+无标注），会报错，训练也有警告

### ISSUE THREAD

**Issue by vs-learner-llg** [open-mmlab/mmocr#1643]
### What is the feature?

训练也会包含一些背景数据，没有标注，本身就为空，应该对该情况做出处理，不应该直接报错

**Comment by gaotongxiao** [comment]
In fact, the background images with empty annotations are _invalid samples_ that contribute _nothing_ to both training and testing. It's still tolerable in training since we can just skip these invalid samples; but test set is important as a universal benchmark to reflect all the model's performance, and any misinterpretation of any test sample may result in biases. Therefore, we intentionally make the program stop on invalid annotations and urge users to check the validity of their dataset.

**Comment by vs-learner-llg** [comment]
> to provide the error message for quickly fixing
![image](https://user-images.githubusercontent.com/50699813/209491868-d16e3382-e464-4b84-b92e-35330c6a7e52.png)

**Comment by vs-learner-llg** [comment]
> 



> In fact, the background images with empty annotations are _invalid samples_ that contribute _nothing_ to both training and testing. It's still tolerable in training since we can just skip these invalid samples; but test set is important as a universal benchmark to reflect all the model's performance, and any misinterpretation of any test sample may result in biases. Therefore, we intentionally make the program stop on invalid annotations and urge users to check the validity of their dataset.

因为一部分的数据容易误检，所以直接加进去，标注为空进行训练，这样对误检会有一定作用，所以有时候也是有用的

**Comment by gaotongxiao** [comment]
In this case, you can annotate these empty samples with a blank space ` `, otherwise these samples would never affect the model.
Also note that you have to use `.json` format for these space annotations instead of `.txt` in MMOCR 0.x. (https://mmocr.readthedocs.io/en/latest/tutorials/blank_recog.html)

**Comment by vs-learner-llg** [comment]
> 可以用空格注释这些空样本` `，否则这些样本永远不会影响模型。
> 另请注意，您必须`.json`为这些空间注释使用格式，而

thank you,tools有直接txt转json的工具嘛

**Comment by gaotongxiao** [comment]
Nope, but I think it's simple to write a python script for conversion.
