### ISSUE TITLE
Error in demo/ocr_image_demo.py script

### ISSUE THREAD

**Issue by narenderkumarnain** [open-mmlab/mmocr#173]
I was trying the demo ocr_image_demo.py script and got this error.
![mmocr_error](https://user-images.githubusercontent.com/59769621/117938827-1278ca80-b325-11eb-86e3-68e93d914616.png)

**Comment by narenderkumarnain** [comment]
I was trying to use the Batch Inference feature added through a pr this morning, It worked well with the detection Model but Fails with the Recognition Model. Not even able to Use inference module with single image in batch (Just image Numpy array as input). The above fix just Suppresses the Batch Inference of Detection as well.  So Recognition models are not yet able to support the Batch Inference or I am missing something?

**Comment by cuhk-hbsun** [comment]
@narenderkumarnain Thanks for your feedback. 
1. Theoretically, for the algorithms using `MultiRotateAugOCR` in `test_pipeline` of `text recognition` or `MultiScaleFlipAug` in `test_pipeline` of `text detection`, the `batch model` is not supported since there may be multiple scaled images for one image.
2. But in practice, there is only one scale in most of the algorithms using `MultiScaleFlipAug`, or one rotate for `MultiRotateAugOCR`, so batch mode can be supported by turn off (ignore) the `aug_test`.
3. I will update the code to support batch mode for both text detection and recognition.

**Comment by cuhk-hbsun** [comment]
@narenderkumarnain I have updated the demo scripts. Please pull the latest code and try again.

**Comment by narenderkumarnain** [comment]
@cuhk-hbsun  It works now. Thanks for the Changes.
