### ISSUE TITLE
SVTR模型中文识别

### ISSUE THREAD

**Issue by wangzixiang99** [open-mmlab/mmocr#1816]
### What is the feature?

您好，我从网上下载了百度的200000张中文裁剪后的数据及其标签文件，并转换成了mmocr支持的json文件格式，但是我使用这批数据集进行训练100epoch后进行文本识别发现，识别结果全为“UKN”，我用mmocr中提供的标签可视化代码查看我的标签发现对于中文标签显示全为框，显示不出来中文字体，请问这是什么原因呢？该框架不支持中文识别吗？还是说代码哪里需要设置呢？

**Comment by gaotongxiao** [comment]
1. You have to specify a Chinese font in config for a successful visualization: https://github.com/open-mmlab/mmocr/pull/1709
2. You may be using a dictionary without Chinese characters, use https://github.com/open-mmlab/mmocr/blob/1.x/dicts/chinese_english_digits.txt instead. Read [docs](https://mmocr.readthedocs.io/en/dev-1.x/get_started/faq.html#text-recognition) Q1 for how to replace the dictionary.

**Comment by wangzixiang99** [comment]
关于这个dictionary的设置是直接将下面这句放到svtr-small_20e_st_mj.py中吗？原本的这个配置文件中并不包含这个字典文件的加载，这块我还是有点迷茫，请问有更具体的文档说明参考吗？
dictionary = dict(
    type='Dictionary',
    dict_file='/my/dict.txt',
    with_start=True,
    with_end=True,
    same_start_end=True,
    with_padding=True,
    with_unknown=True)

**Comment by wangzixiang99** [comment]
> 1. You have to specify a Chinese font in config for a successful visualization: [[Feature] add a new argument font_properties to set a specific font file in order to draw Chinese characters properly #1709](https://github.com/open-mmlab/mmocr/pull/1709)
> 2. You may be using a dictionary without Chinese characters, use https://github.com/open-mmlab/mmocr/blob/1.x/dicts/chinese_english_digits.txt instead. Read [docs](https://mmocr.readthedocs.io/en/dev-1.x/get_started/faq.html#text-recognition) Q1 for how to replace the dictionary.

这个在配置中指定中文字体具体是在哪个配置文件中增加呢？以及如何增加？我目前显示时依旧无法显示中文，log文件显示UserWarning: Glyph 35843 (\N{CJK UNIFIED IDEOGRAPH-8C03}) missing from current font.

**Comment by gaotongxiao** [comment]
Dictionary was configured in `configs/textrecog/svtr/_base_svtr-tiny.py` and inherited by `svtr-small_20e_st_mj.py`. Just mody the base config.

Similarly, visualizer is placed at `configs/textrecog/_base_/default_runtime.py`

Seems you are not familiar with the config system. Read through the [config](https://mmocr.readthedocs.io/en/dev-1.x/user_guides/config.html) docs can be helpful, with extra attention on:

https://mmocr.readthedocs.io/en/dev-1.x/user_guides/config.html#configuration-inheritance
https://mmocr.readthedocs.io/en/dev-1.x/user_guides/config.html#visualization-configuration

**Comment by gaotongxiao** [comment]
Right, you need to prepare a Chinese font and point the visualizer to it.

**Comment by wangzixiang99** [comment]
> Chinese font

Q1：您好，我已经在configs/textrecog/svtr/svtr-small_20e_st_mj.py中增加了如下配置：

vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='TextRecogLocalVisualizer',
    name='visualizer',
    vis_backends=vis_backends,
    font_properties='simsun.ttc')

dictionary = dict(
    type='Dictionary',
    dict_file='/home/wang/code/mmocr-1.x/chinese_english_digits.txt',
    with_start=True,
    with_end=True,
    same_start_end=True,
    with_padding=True,
    with_unknown=True)

字体文件也已经下载到了指定路径，用可视化指令python tools/analysis_tools/browse_dataset.py configs/textrecog/_base_/datasets/recog_baidudata_chinese.py显示出来的数据依然无法正常显示中文。

Q2：同时调用MMOCRInferencer接口对图片进行推理时，得到的结果依然为“UKN”，这是否也是因为中文字体无法显示的原因呢？“UKN”的个数和图中文字个数基本都能对得上

请问是否还有其他地方需要设置或者修改的呢？

**Comment by gaotongxiao** [comment]
1.  Your modification hasn't been applied to `configs/textrecog/base/datasets/recog_baidudata_chinese.py`. Try `python tools/analysis_tools/browse_dataset.py configs/textrecog/svtr/svtr-small_20e_st_mj.py`.
2. The released SVTR weights were trained in English only, and therefore cannot recognize Chinese. You have to train your SVTR from scratch on the Chinese dataset, and use your weight & config for inference.

**Comment by wangzixiang99** [comment]
> 1. Your modification hasn't been applied to `configs/textrecog/base/datasets/recog_baidudata_chinese.py`. Try `python tools/analysis_tools/browse_dataset.py configs/textrecog/svtr/svtr-small_20e_st_mj.py`.
> 2. The released SVTR weights were trained in English only, and therefore cannot recognize Chinese. You have to train your SVTR from scratch on the Chinese dataset, and use your weight & config for inference.

您好，非常感谢您的耐心指导，数据可视化问题已经可以正常显示中文了
我已经在configs/textrecog/svtr/_base_svtr-tiny.py中修改了如下配置：
dictionary = dict(
type='Dictionary',
dict_file='{{ fileDirname }}/../../../dicts/chinese_english_digits.txt',
with_padding=True,
with_unknown=True,
)
但是推理时得到的结果不再是“UKN”，但是全为不正确的繁体字，请问一下这个dictionary中包含的chinese_english_digits.txt里面的所有中文是不是需要覆盖我的数据集中的所有中文呢？如果我的推理图片中出现了该txt中未曾包含的文字，那就会推理出错误文字吗？

**Comment by wangzixiang99** [comment]
Q1：那dict所对应的txt文件中的文字是不是越多越好呢？还是说只需要尽可能包含我的数据集可能出现的一些文字即可？

Q2：这个dict文件的具体作用是啥啊？只有标签还不足够模型来学习其特征吗？

Q3：我用官方的转换代码来将其他数据集转成了该框架支持的json文件格式，但是打开json时发现，所有中文均被显示为\uff21\uff2e\uff35\uff26\uff21编码格式，之后我把mmocr/utils/data_converter_utils.py文件中的
mmengine.dump(out_json, out_json_name, **kwargs)——>修改为mmengine.dump(out_json, out_json_name, **kwargs, ensure_ascii=False)后json文件可以正常显示中文了，那我训练时加载的json文件是加载\uff21这种形式的json文件还是加载正常显示中文的那种json文件呢？

Q4：我下载很多公开数据集的json文件中打开后都是\uff21这种形式的，是否需要将其转成中文形式才能正常训练？还是以编码方式直接训练？

**Comment by gaotongxiao** [comment]
To Q1, Q2:

A dictionary file is essential in text recognition tasks because it serves as a reference for converting the model's output into human-readable text. In the context of text recognition, a dictionary file typically contains a list of characters, symbols, or tokens that the model can recognize. These elements make up the vocabulary that the model uses to transcribe the text from images or other input sources.

During training, it helps the model learn to map the outputs to the corresponding characters or tokens in the dictionary.
During inference, it is used to convert the model's output (usually a sequence of indices) back into human-readable text.
As for the size of the dictionary, it depends on the problem domain and the complexity of the text that the model needs to recognize. A larger dictionary might allow the model to recognize a more extensive range of characters, symbols, and tokens, potentially improving its overall performance. However, a larger dictionary can also introduce more complexity and may require a larger training dataset to achieve good results.

It is essential to strike a balance between the dictionary size and the model's ability to learn effectively. A too-small dictionary might lead to poor recognition performance, while an unnecessarily large dictionary can result in increased complexity, longer training times, and the need for more extensive training data. To achieve optimal performance, it's crucial to select a dictionary size that is appropriate for the specific problem domain and dataset.

Q3, Q4: Use the `ensure_ascii=False` one.
