### ISSUE TITLE
classifier for psenet

### ISSUE THREAD

**Issue by priyanshu-sinha-trysolvio** [open-mmlab/mmocr#186]
How to add multi-class support for psenet? or any other text detection models.

**Comment by innerlee** [comment]
Could you give more detailed explanation on the feature request?

**Comment by priyanshu-sinha-trysolvio** [comment]
I was trying to add multiple class labels for different types of bounding box detection. Mathematical Equations, chemistry formulas and normal text. These can be the classes which can help the model differentiate better.

**Comment by jeffreykuang** [comment]
> I was trying to add multiple class labels for different types of bounding box detection. Mathematical Equations, chemistry formulas and normal text. These can be the classes which can help the model differentiate better.

It needs to modify much code to achieve this feature since we assume there are only one class. Namely, text. 
According to my experience,  there is no much recall difference between considering them as one class and considering them as three classes.   However, if you want to distinguish them,  I suggest to use a classifier, followed by the text detector.

**Comment by priyanshu-sinha-trysolvio** [comment]
Yeah It seems a much effective and efficient way to do it.
