### ISSUE TITLE
[Docs] val_evaluator = dict(     dataset_prefixes=['CUTE80', 'IIIT5K', 'SVT', 'SVTP', 'IC13', 'IC15']) test_evaluator = val_evaluator When I use my own data, how do I go about changing it？

### ISSUE THREAD

**Issue by OuXiao514** [open-mmlab/mmocr#1906]
### Branch

master branch  https://mmocr.readthedocs.io/en/latest/

### 📚 The doc issue

val_evaluator = dict(
    dataset_prefixes=['CUTE80', 'IIIT5K', 'SVT', 'SVTP', 'IC13', 'IC15'])
test_evaluator = val_evaluator
When I use my own data, how do I go about changing it？

### Suggest a potential alternative/fix

val_evaluator = dict(
    dataset_prefixes=['CUTE80', 'IIIT5K', 'SVT', 'SVTP', 'IC13', 'IC15'])
test_evaluator = val_evaluator
When I use my own data, how do I go about changing it？

**Comment by gaotongxiao** [comment]
Just change the strings in `dataset_prefixes` so that these prefixes match the order in which the datasets are concatenated in `val_dataloader.dataset`. An example here:

https://github.com/open-mmlab/mmocr/blob/58ea06d9867ca2b4ccb60bcae499964ed2b7c242/configs/textrecog/crnn/crnn_mini-vgg_5e_toy.py#L40-L41
