### ISSUE TITLE
SDMGR Model Labels

### ISSUE THREAD

**Issue by neerajhbhat** [open-mmlab/mmocr#231]
Hi!
(Really appreciating your work!!)

I was able to run the KIE checkpoint model on the WildReceipt test dataset. The results were really interesting. However, I've some questions:

1. If I were to extract the information from my own receipts, I would have to give it the image and the annotations(bboxes and text). Does it expect line block level bounding boxes or word block level bounding boxes?
2. Had a look at the test.txt in WildReceipt dataset, the text for each box does not contain any spaces, and there is no text corresponding to some bounding boxes, where there should have been . Is it how the model was trained?

For example 

For the given test image, (image_files/Image_29/14/713c04800cd0b0c269e06c89f6f2b629e3776002.jpeg)
![image](https://user-images.githubusercontent.com/28949967/119272018-b6b21980-bc21-11eb-8b12-35561453e839.png)
the labels are
![image](https://user-images.githubusercontent.com/28949967/119272115-1c060a80-bc22-11eb-8824-0a9449780a27.png)

@innerlee @cuhk-hbsun Please help me out here.

**Comment by cuhk-hbsun** [comment]
Thanks for your question.
1. Line level bounding box will be better. Exactly speaking, each key or value(may contain several words) in one box will be better. 
2. We remove the space between words since there is no character in the dictionary file corresponding to space. We will find a way to solve it in the following version.
3. For text which is not clear to see by human annotator, it will be empty. If you get the `text` by the OCR system, just use the recognition results.

**Comment by neerajhbhat** [comment]
Thank you so much!

**Comment by cuhk-hbsun** [comment]
fix
