### ISSUE TITLE
你好，想请问下，如果OCR模型（如NRTR）转成torchscript或者onnx之后，img_meta应该怎么输入进去？

### ISSUE THREAD

**Issue by cjt222** [open-mmlab/mmocr#445]
模型结构中NRTR的encoder和decoder都会用到img_meta中的valid_ratio，这个如何加进去呢？

**Comment by cjt222** [comment]
因为torchscript的输入是tensor，而img_meta中数据都是int型，这个如何把它们组合输入呢？

**Comment by gaotongxiao** [comment]
`TFEncoder` and `TFDecoder` use `valid_ratio` to dynamically generate masks for the attention module if the width of the resized image doesn't fill up the image tensor. My personal suggestion for now is to keep the image aspect ratio the same as the image that you used to export the model, so that the model retains its expected behavior.
