### ISSUE TITLE
about measure parameters

### ISSUE THREAD

**Issue by lantx5** [open-mmlab/mmocr#493]
Is a tool provided to measure the number of NRTR parameters?thanks

**Comment by gaotongxiao** [comment]
MMCV has provided `get_model_complexity_info` in `mmcv.cnn.utils` that can count FLOPs of a model. But NRTR is not compatible with it yet, because `get_model_complexity_info` only accepts input as a tensor shape while our models, including NRTR, need extra info from `img_metas` as an additional argument. Some other repos support this util by implementing a 'forward_dummy` function which doesn't take `img_metas` into account. If you're interested and want to contribute, you may refer to their implementations. Here is an example from MMSeg:

https://github.com/open-mmlab/mmsegmentation/blob/master/tools/get_flops.py
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/encoder_decoder.py#L116
