### ISSUE TITLE
Visualize with gt_labels in Recognizer model

### ISSUE THREAD

**Issue by yellowjs0304** [open-mmlab/mmocr#686]
Hi, I wonder how to visualize pred-labels and gt_labels too.
I found there's gt_label args in [imshow_text_label](https://github.com/open-mmlab/mmocr/blob/fb1892a1aebc930836c1da8588bbc645b879e41f/mmocr/core/visualize.py#L364) function, and this is called by [mmocr/apis/test.py](https://github.com/open-mmlab/mmocr/blob/fb1892a1aebc930836c1da8588bbc645b879e41f/mmocr/apis/test.py#L142) .

And It looks like can be receive "gt_labels" value from data-loader but, when I followed the pipeline but, it seems like that there's no 'gt_labels' option in recognizer test dataloader.
If not so, where i should modified? Is there something what i missed?

**Comment by cuhk-hbsun** [comment]
For `textrecog`, there are two ways to show the `gt_label`: (task `crnn` for example)
1. If you use script `python tools/test.py <config_file> <checkpoint> --show-dir <out_dir>`,
   1.1 Add `img_norm_cfg`, `ori_filename`, `img_shape`, `ori_shape` and `text` in [meta_keys](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_pipelines/crnn_pipeline.py#L31)
   1.2 modify [code](https://github.com/open-mmlab/mmocr/blob/fb1892a1aebc930836c1da8588bbc645b879e41f/mmocr/apis/test.py#L142) to
       ```pyhton
       gt_label = img_meta['text']
       model.module.show_result(
                        img_show,
                        result[j],
                        gt_label=gt_label,
                        show=show,
                        out_file=out_file,
                        score_thr=show_score_thr)
       ```

2. We prefer to use script `python tools/recog_test_imgs.py <img_prefix> <ann_file> <config_file> <checkpoint> --out-dir <out_dir>`, since no code need to be modified.

**Comment by yellowjs0304** [comment]
Got it! It's really helpful~ Thank you for fast reply.
