### ISSUE TITLE
Trained on tokens/words, but predicts sentences at inference time

### ISSUE THREAD

**Issue by purnasai** [open-mmlab/mmocr#784]
I annotated simulated data to train Detection models in mmocr. I used 'PS_IC15' to train. sample annotated images below. 
![image](https://user-images.githubusercontent.com/25660247/154051068-29354f4c-44e3-4d7a-987d-b6e21fb82672.png)

at inference time, model predictions looks as below.
![Screenshot from 2022-02-15 16-50-09](https://user-images.githubusercontent.com/25660247/154052034-c048631c-d11e-49fb-bd18-91f8466d2be4.png)

Is there any way, that I can detect only text, not the entire sentence of the line at employeeID, Department, Issue date, and Blood group like in the first image? or any other post-processing step that can do this with some threshold change in an argument?

**Comment by gaotongxiao** [comment]
A text detection model usually groups words based on their spatial relations, which unfortunately is not applicable to your case. You may try the following three possible ways:
- The simplest one is to leave it as it is, pass it to a recognizer, and split words with colons
-  Re-annotate your dataset so that each box bounds exactly a word, and merge these boxes based on the content afterward
- Use significantly more data to train
