### ISSUE TITLE
DBNet detects only half the image

### ISSUE THREAD

**Issue by seekingdeep** [open-mmlab/mmocr#85]
Hi there,
When using DBNet for prediction, both res18 and res50
only half the image is predicted, leaving the top part.
![db50](https://user-images.githubusercontent.com/71519088/115118373-8a183b80-9fab-11eb-8da4-f3170651e2f1.jpg)

main
![2](https://user-images.githubusercontent.com/71519088/115118389-9a301b00-9fab-11eb-8f74-1b37440bd244.jpg)

**Comment by cuhk-hbsun** [comment]
Thanks for your feedback. We are locating the bug.

**Comment by jeffreykuang** [comment]
> Hi there,
> When using DBNet for prediction, both res18 and res50
> only half the image is predicted, leaving the top part.
> ![db50](https://user-images.githubusercontent.com/71519088/115118373-8a183b80-9fab-11eb-8da4-f3170651e2f1.jpg)
> 
> main
> ![2](https://user-images.githubusercontent.com/71519088/115118389-9a301b00-9fab-11eb-8f74-1b37440bd244.jpg)

Thanks for bug report.
I  guess it is due to the default max candidate number in the post process of dbnet.
https://github.com/open-mmlab/mmocr/blob/a68de2214a4d575761d6355e8b425e7eea7a6d99/mmocr/models/textdet/postprocess/wrapper.py#L189

I will run your image and validate it.  If the answer is yes,   I will expose this parameter to the dbnet config so that the max candidate number can be settable.   You can change it to a large number such as 3000 to work around this issue.

**Comment by jeffreykuang** [comment]
When the max candidate number is set to 3000, the result is correct. It is shown as follows:
![image](https://user-images.githubusercontent.com/17879798/115147410-6a594400-a08d-11eb-9920-bf4fcdd48a3b.png)

**Comment by seekingdeep** [comment]
@jeffreykuang @cuhk-hbsun 
This solved the issue, good job
```
 max_candidates=3000): 
```
