### ISSUE TITLE
own dataset

### ISSUE THREAD

**Issue by happy20200** [open-mmlab/mmocr#859]
训练自己的数据集，提示有的点坐标不是顺时针，这个是怎么回事啊，同样的做法，有的标签能过去，有的标签过不去报错
![1647861559(1)](https://user-images.githubusercontent.com/59427046/159250810-93eea8db-7b98-4953-9530-a88060024b8f.png)
![1647861611(1)](https://user-images.githubusercontent.com/59427046/159250921-d1c54ff4-100d-4594-9b98-391ec3534d06.png)
应该怎么改啊，谢谢~

**Comment by xinke-wang** [comment]
The error message is obvious. There are bounding boxes in your custom dataset that do not follow clockwise order (this may be because the annotators did not label the bounding box in clockwise order). You have to write a converter to reorder those annotations to ensure the coordinates of bounding quadrilaterals follow a clockwise order, otherwise, such samples may introduce confusions to the text detector during training.

**Comment by gaotongxiao** [comment]
MMOCR has a handy function [`sort_points`](https://mmocr.readthedocs.io/en/latest/api.html?highlight=sort_points#mmocr.utils.sort_points) that reorders points in clockwise order. But it's still experimental and could fail in some cases.
