### ISSUE TITLE
recog training for chinese

### ISSUE THREAD

**Issue by liuke97** [open-mmlab/mmocr#865]
1.only sar_ch for chinese recog?
2.I have made a dataset for chinese recog, can I use CRNN, SegOCR or other models to train ? How is the command ? In fact ,I am not sure if it is ok to train based on the pretrained model you give  ,or I need to start training from zero? And to use which configs.

Thank you for answering.

**Comment by xinke-wang** [comment]
1. You can use any recognition model to train with Chinese data. But MMOCR currently only provides SAR pre-trained model for Chinese recognition.
2. Since the currently released models were trained on English data only, it's better to train your own model from scratch.
3. Please refer to the [Doc](https://mmocr.readthedocs.io/en/latest/training.html) to see the training command.
4. For configs, if you would like to train on a customized dataset, you need to write a dataset config (see [ST_MJ_train.py](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_datasets/ST_MJ_train.py) as an example).
5. For training with Chinese data, you need also to modify the `dict_type` in the method config file. For example, the default `dict_type` for [crnn](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_models/crnn.py) is `DICT36`, which only supports English texts.

please also refer to issue #243
