### ISSUE TITLE
请问MultiscaleFlipAug中两个img_scale有什么区别呢

### ISSUE THREAD

**Issue by ocrhei** [open-mmlab/mmocr#888]
按我的理解，第一个image_scale就已经是把原图给resize了，为啥还要再来一个resize呢，而且您看这两个img_scale的尺寸有时还相差巨大
![qxlarge-dsc-124D099FE58C275F9A29A4E48A32C6A4](https://user-images.githubusercontent.com/92171181/160352708-d4d07ef4-e137-4754-b88e-61ae7a2ea17a.jpg)

**Comment by gaotongxiao** [comment]
Sorry for the confusion, the `Resize` transform prefers the `img_scale` in `MultiScaleFlipAug`, meaning that in this case the image will be resized to `img_scale_test_icdar2015` instead of `(3000, 640)`. In fact, the second `img_scale` can be removed from the config to avoid further confusion. We'd appreciate it if you could raise a PR for it :)
