### ISSUE TITLE
About the academic performance of the ABINet?

### ISSUE THREAD

**Issue by simplify23** [open-mmlab/mmocr#999]
Hi, I am trying to restore the report accuracy of ABINet using academic config. Without employing the pre-trained language model, only 90.61% avg was attained, considerably lower than the reported avg of 91.48%. What's the reason? What is the difference between utilizing the pre-trained language model provided by the official code in the readme and direct training? In ABINet's report, AVG 91.48% comes exclusively from MJ and ST data sets. Why is pre-training needed? Where can I recover the 0.8% accuracy gap， except using the pre-trained model?
i get using mmocr abinet traing without pre-trained model:
`0.9543, 1_word_acc_ignore_case_symbol: 0.9335, 2_word_acc_ignore_case_symbol: 0.9448, 3_word_acc_ignore_case_symbol: 0.8368, 4_word_acc_ignore_case_symbol: 0.8713, 5_word_acc_ignore_case_symbol: 0.8958, mean_word_acc_ignore_case_symbol: 0.9061`

abinet result with pre-trained model:
`96.5	93.2	 95.1 85.9	 89	89.2	    91.48333333`

**Comment by xinke-wang** [comment]
ABINet proposes an iterative language model to improve recognition accuracy, which fuses language features to refine the vision prediction. 

Since MMOCR does not have a systematic pipeline to pre-train the language model, we directly converted the weights of the language module from the officially released models by the authors, that is why a pre-trained model is needed here.

If you do not use a pre-trained language model, then that will be a vision-only model without a language rectifying mechanism,  which leads to the performance gap.
